/* Дополнительный словарь: главная, Practice Lab, профиль, сообщество (ru/uk/ar). */
(() => {
  const I = window.VA_I18N;
  Object.assign(I.ru, {
    brand_sub: "мини-приложение", home_hero_sub: "Каждый урок приближает тебя к финансовой свободе.", home_tag: "Сильнее каждый день",
    your_progress: "Твой прогресс", of_course: "курса", lessons_progress: "Пройдено {done} из {total} уроков", continue_learning: "Продолжить обучение", all_lessons: "Все уроки академии", show_all: "Показать все ({n})", hide: "Свернуть",
    practice_hero_sub: "Закрепляй знания на реальных рыночных ситуациях", practice_tag: "Практика делает трейдера", solved: "Решено задач", accuracy: "Верных ответов", streak_days: "Дней подряд",
    task_n: "Задача {a} из {b}", diff_easy: "Лёгкий", diff_medium: "Средний", diff_hard: "Сложный", question: "Что делать в этой ситуации?",
    opt_a_sub: "вход по структуре вверх", opt_b_sub: "вход по структуре вниз", opt_c: "Дождаться подтверждения", opt_c_sub: "и войти позже", opt_d: "Не входить", opt_d_sub: "Сейчас лучше быть вне рынка",
    mentor_tip: "Совет от Волчка", check_answer: "Проверить ответ →", next_task: "Следующее задание →", play: "Пуск", pause: "Пауза", replay: "Повтор",
    filter_all: "Все", diff_all: "Любая сложность", weak_mode: "Потренировать слабые темы", no_tasks: "По этому фильтру заданий нет", solved_before: "Режим повторения — XP уже начислен", xp_gain: "+{n} XP",
    cat_candles: "Свечи", cat_trend: "Тренд", cat_levels: "Уровни", cat_indicators: "Индикаторы", cat_psychology: "Психология", cat_timeframes: "Таймфреймы", cat_reversals: "Развороты", cat_entry: "Точки входа", cat_context: "Контекст рынка",
    profile_hero: "Твой профиль", profile_hero_sub: "Путь к финансовой свободе продолжается", quote_1: "Дисциплина сегодня — твоя свобода завтра.", quote_by: "Твой наставник Vovchok",
    overall: "Общий прогресс", modules_done_of: "Пройдено {a} из {b} модулей", on_track: "Ты на правильном пути. Продолжай!", xp_title: "Опыт (XP)", xp_sub: "За обучение и активность",
    level_title: "Текущий уровень", level_n: "Уровень {n}", to_next: "{n} XP до следующего", level_max: "Максимальный уровень", level_names: ["Новичок", "Ученик", "Трейдер", "Аналитик", "Мастер"],
    modules_title: "Пройдено модулей", modules_left: "Осталось {n} модулей", streak_title: "Серия дней", days_n: "{n} дней", streak_sub: "Знания становятся привычкой",
    ach_title: "Достижения", ach_all: "Все достижения", ach_locked: "Закрыто", ach_unlocked: "Открыто", level_up: "Новый уровень!", ach_unlock_toast: "Достижение открыто: {name}",
    ach_first_step: "Первый шаг", ach_first_step_d: "Завершить первый урок", ach_five_lessons: "В ритме", ach_five_lessons_d: "Пройти 5 уроков", ach_practitioner: "Практик", ach_practitioner_d: "Решить 10 практических заданий",
    ach_sharp: "Точный глаз", ach_sharp_d: "Точность 80% при 5+ ответах", ach_streak3: "Три дня", ach_streak3_d: "Учиться 3 дня подряд", ach_streak7: "Серия", ach_streak7_d: "Учиться 7 дней подряд",
    ach_candle_expert: "Свечной эксперт", ach_candle_expert_d: "Завершить модуль «Японские свечи»", ach_final: "Финал", ach_final_d: "Закончить всю академию",
    stats_title: "Статистика обучения", st_lessons: "уроков", st_practices: "практических заданий", st_accuracy: "правильных ответов", st_days: "дней обучения",
    weak_title: "Что стоит повторить", repeat_topic: "Повторить тему", weak_empty: "Реши несколько практик — я покажу, что стоит повторить.", lang_title: "Язык интерфейса",
    motto: "Маленькие шаги каждый день приводят к большим результатам", dev_reset: "Сбросить beta-прогресс",
    community_hero: "Будь среди тех, кто развивается.", community_hero_sub: "Обучение. Практика. Поддержка. Реальные возможности.", community_tag: "Вместе мы сильнее",
    official_channel: "Официальный канал", channel_desc: "Новости, обучающие материалы, полезные разборы и важные обновления.", go_channel: "Перейти в канал ↗",
    our_partner: "Наш партнёр", partner_desc: "Платформа-партнёр VOVCHOK ACADEMY.", go_partner: "Перейти к партнёру ↗", community_quote: "Сильное окружение помогает тебе расти.", ask_ai: "Спросить Волчка, почему", ai_thinking: "Волчок думает…", ai_error: "Наставник сейчас недоступен. Попробуй позже."
  });
  Object.assign(I.uk, {
    brand_sub: "міні-застосунок", home_hero_sub: "Кожен урок наближає тебе до фінансової свободи.", home_tag: "Сильніше щодня",
    your_progress: "Твій прогрес", of_course: "курсу", lessons_progress: "Пройдено {done} із {total} уроків", continue_learning: "Продовжити навчання", all_lessons: "Усі уроки академії", show_all: "Показати всі ({n})", hide: "Згорнути",
    practice_hero_sub: "Закріплюй знання на реальних ринкових ситуаціях", practice_tag: "Практика робить трейдера", solved: "Вирішено задач", accuracy: "Правильних відповідей", streak_days: "Днів підряд",
    task_n: "Задача {a} з {b}", diff_easy: "Легкий", diff_medium: "Середній", diff_hard: "Складний", question: "Що робити в цій ситуації?",
    opt_a_sub: "вхід за структурою вгору", opt_b_sub: "вхід за структурою вниз", opt_c: "Дочекатися підтвердження", opt_c_sub: "і увійти пізніше", opt_d: "Не входити", opt_d_sub: "Зараз краще бути поза ринком",
    mentor_tip: "Порада від Вовчика", check_answer: "Перевірити відповідь →", next_task: "Наступне завдання →", play: "Пуск", pause: "Пауза", replay: "Повтор",
    filter_all: "Усі", diff_all: "Будь-яка складність", weak_mode: "Потренувати слабкі теми", no_tasks: "За цим фільтром завдань немає", solved_before: "Режим повторення — XP уже нараховано", xp_gain: "+{n} XP",
    cat_candles: "Свічки", cat_trend: "Тренд", cat_levels: "Рівні", cat_indicators: "Індикатори", cat_psychology: "Психологія", cat_timeframes: "Таймфрейми", cat_reversals: "Розвороти", cat_entry: "Точки входу", cat_context: "Контекст ринку",
    profile_hero: "Твій профіль", profile_hero_sub: "Шлях до фінансової свободи триває", quote_1: "Дисципліна сьогодні — твоя свобода завтра.", quote_by: "Твій наставник Vovchok",
    overall: "Загальний прогрес", modules_done_of: "Пройдено {a} з {b} модулів", on_track: "Ти на правильному шляху. Продовжуй!", xp_title: "Досвід (XP)", xp_sub: "За навчання та активність",
    level_title: "Поточний рівень", level_n: "Рівень {n}", to_next: "{n} XP до наступного", level_max: "Максимальний рівень", level_names: ["Новачок", "Учень", "Трейдер", "Аналітик", "Майстер"],
    modules_title: "Пройдено модулів", modules_left: "Залишилося {n} модулів", streak_title: "Серія днів", days_n: "{n} днів", streak_sub: "Знання стають звичкою",
    ach_title: "Досягнення", ach_all: "Усі досягнення", ach_locked: "Закрито", ach_unlocked: "Відкрито", level_up: "Новий рівень!", ach_unlock_toast: "Досягнення відкрито: {name}",
    ach_first_step: "Перший крок", ach_first_step_d: "Завершити перший урок", ach_five_lessons: "У ритмі", ach_five_lessons_d: "Пройти 5 уроків", ach_practitioner: "Практик", ach_practitioner_d: "Вирішити 10 практичних завдань",
    ach_sharp: "Точне око", ach_sharp_d: "Точність 80% при 5+ відповідях", ach_streak3: "Три дні", ach_streak3_d: "Навчатися 3 дні підряд", ach_streak7: "Серія", ach_streak7_d: "Навчатися 7 днів підряд",
    ach_candle_expert: "Свічковий експерт", ach_candle_expert_d: "Завершити модуль «Японські свічки»", ach_final: "Фінал", ach_final_d: "Закінчити всю академію",
    stats_title: "Статистика навчання", st_lessons: "уроків", st_practices: "практичних завдань", st_accuracy: "правильних відповідей", st_days: "днів навчання",
    weak_title: "Що варто повторити", repeat_topic: "Повторити тему", weak_empty: "Виріши кілька практик — я покажу, що варто повторити.", lang_title: "Мова інтерфейсу",
    motto: "Маленькі кроки щодня ведуть до великих результатів", dev_reset: "Скинути beta-прогрес",
    community_hero: "Будь серед тих, хто розвивається.", community_hero_sub: "Навчання. Практика. Підтримка. Реальні можливості.", community_tag: "Разом ми сильніші",
    official_channel: "Офіційний канал", channel_desc: "Новини, навчальні матеріали, корисні розбори та важливі оновлення.", go_channel: "Перейти в канал ↗",
    our_partner: "Наш партнер", partner_desc: "Платформа-партнер VOVCHOK ACADEMY.", go_partner: "Перейти до партнера ↗", community_quote: "Сильне оточення допомагає тобі зростати.", ask_ai: "Запитати Вовчика, чому", ai_thinking: "Вовчик думає…", ai_error: "Наставник зараз недоступний. Спробуй пізніше."
  });
  Object.assign(I.ar, {
    brand_sub: "تطبيق صغير", home_hero_sub: "كل درس يقرّبك من الحرية المالية.", home_tag: "أقوى كل يوم",
    your_progress: "تقدّمك", of_course: "من الدورة", lessons_progress: "أُنجز {done} من {total} درساً", continue_learning: "متابعة التعلّم", all_lessons: "كل دروس الأكاديمية", show_all: "عرض الكل ({n})", hide: "طيّ",
    practice_hero_sub: "ثبّت معرفتك على مواقف سوق حقيقية", practice_tag: "التدريب يصنع المتداول", solved: "مهام محلولة", accuracy: "إجابات صحيحة", streak_days: "أيام متتالية",
    task_n: "المهمة {a} من {b}", diff_easy: "سهل", diff_medium: "متوسط", diff_hard: "صعب", question: "ما العمل في هذا الموقف؟",
    opt_a_sub: "دخول مع بنية صاعدة", opt_b_sub: "دخول مع بنية هابطة", opt_c: "انتظار التأكيد", opt_c_sub: "والدخول لاحقاً", opt_d: "عدم الدخول", opt_d_sub: "الأفضل الآن البقاء خارج السوق",
    mentor_tip: "نصيحة فولتشوك", check_answer: "← تحقق من الإجابة", next_task: "← المهمة التالية", play: "تشغيل", pause: "إيقاف", replay: "إعادة",
    filter_all: "الكل", diff_all: "أي صعوبة", weak_mode: "تدريب المواضيع الضعيفة", no_tasks: "لا مهام لهذا المرشّح", solved_before: "وضع المراجعة — XP مُنح سابقاً", xp_gain: "+{n} XP",
    cat_candles: "الشموع", cat_trend: "الاتجاه", cat_levels: "المستويات", cat_indicators: "المؤشرات", cat_psychology: "علم النفس", cat_timeframes: "الأطر الزمنية", cat_reversals: "الانعكاسات", cat_entry: "نقاط الدخول", cat_context: "سياق السوق",
    profile_hero: "ملفك الشخصي", profile_hero_sub: "الطريق إلى الحرية المالية مستمر", quote_1: "الانضباط اليوم — حريتك غداً.", quote_by: "مرشدك Vovchok",
    overall: "التقدّم العام", modules_done_of: "أُنجز {a} من {b} وحدة", on_track: "أنت على الطريق الصحيح. واصل!", xp_title: "الخبرة (XP)", xp_sub: "للتعلّم والنشاط",
    level_title: "المستوى الحالي", level_n: "المستوى {n}", to_next: "{n} XP حتى التالي", level_max: "أعلى مستوى", level_names: ["مبتدئ", "متعلّم", "متداول", "محلّل", "خبير"],
    modules_title: "وحدات مُنجزة", modules_left: "بقي {n} وحدات", streak_title: "سلسلة الأيام", days_n: "{n} أيام", streak_sub: "المعرفة تصبح عادة",
    ach_title: "الإنجازات", ach_all: "كل الإنجازات", ach_locked: "مقفل", ach_unlocked: "مفتوح", level_up: "مستوى جديد!", ach_unlock_toast: "إنجاز مفتوح: {name}",
    ach_first_step: "الخطوة الأولى", ach_first_step_d: "إنهاء الدرس الأول", ach_five_lessons: "في الإيقاع", ach_five_lessons_d: "إنجاز 5 دروس", ach_practitioner: "ممارس", ach_practitioner_d: "حل 10 مهام تدريبية",
    ach_sharp: "عين دقيقة", ach_sharp_d: "دقة 80% مع 5+ إجابات", ach_streak3: "ثلاثة أيام", ach_streak3_d: "التعلّم 3 أيام متتالية", ach_streak7: "سلسلة", ach_streak7_d: "التعلّم 7 أيام متتالية",
    ach_candle_expert: "خبير الشموع", ach_candle_expert_d: "إنهاء وحدة «الشموع اليابانية»", ach_final: "الختام", ach_final_d: "إنهاء الأكاديمية كاملة",
    stats_title: "إحصاءات التعلّم", st_lessons: "دروس", st_practices: "مهام تدريبية", st_accuracy: "إجابات صحيحة", st_days: "أيام تعلّم",
    weak_title: "ما يستحق المراجعة", repeat_topic: "مراجعة الموضوع", weak_empty: "حلّ بعض التدريبات — وسأريك ما يستحق المراجعة.", lang_title: "لغة الواجهة",
    motto: "خطوات صغيرة كل يوم تقود إلى نتائج كبيرة", dev_reset: "إعادة تعيين تقدّم البيتا",
    community_hero: "كن بين من يتطوّرون.", community_hero_sub: "تعلّم. تدريب. دعم. فرص حقيقية.", community_tag: "معاً أقوى",
    official_channel: "القناة الرسمية", channel_desc: "أخبار، مواد تعليمية، تحليلات مفيدة وتحديثات مهمة.", go_channel: "↗ الانتقال إلى القناة",
    our_partner: "شريكنا", partner_desc: "المنصة الشريكة لـ VOVCHOK ACADEMY.", go_partner: "↗ الانتقال إلى الشريك", community_quote: "البيئة القوية تساعدك على النمو.", ask_ai: "اسأل فولتشوك لماذا", ai_thinking: "فولتشوك يفكّر…", ai_error: "المرشد غير متاح الآن. حاول لاحقاً."
  });
})();
